name: haskell-first-layer-feedback
version: 0.1.0.0
github: "jairojuunior/haskell-first-layer-feedback"
license: BSD3
author: "Jairo da Silva Freitas Júnior"
maintainer: "example@example.com"
copyright: "2021 Jairo da Silva Freitas Júnior"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/semana03#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  haskell-first-layer-feedback-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-first-layer-feedback
      - tasty
      - tasty-hunit
      - tasty-quickcheck