name: Basic submission verifications
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: haskell:9.0.2
    steps:
      - uses: actions/checkout@v2
      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"
      - name: Build code
        run: stack build --allow-different-user
      - name: Notify student if code did not build
        if: failure()
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
          "title": "[AUTO] Seu c처digo n찾o compilou",
          "body": "Este issue foi aberto automaticamente pois o commit _${{ github.sha }}_ n찾o compilou.\n\n Encerre este issue antes de realizar uma nova submiss찾o para evitar que se confunda. \n\n Bons estudos!",
          "assignees": ["${{ github.actor }}"]
          }'
      - name: Run public tests
        run: stack test > test_result.log
      - name: Count number of successful tests
        if: failure()
        id: count_success
        run: echo "::set-output name=oks::$(cat test_result.log | grep "OK" | wc -l)\n"
      - name: Notify student if code failed all tests
        if: steps.count_success.outputs.oks == 3
        run: echo "Failed all tests"


